# LNMP Microservice
version: "3"
services:

  nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # app
      - ./app:/var/www/app
      # nginx configs
      - ./docker-conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-conf/nginx/conf.d/:/etc/nginx/conf.d/
      # certificates
      - ./docker-conf/nginx/ca/server.crt/:/etc/nginx/server.crt
      - ./docker-conf/nginx/ca/server.key/:/etc/nginx/server.key
    links:
      - php

  # php
  php:
    build: ./docker-conf/php
    container_name: app_php
    ports:
      - "9000"
    volumes:
      - ./app:/var/www/app
      # Your php.ini
      - ./docker-conf/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql

  # database
  mysql:
    image: mysql:latest
    container_name: app_mysql
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
